### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yangit** [fritzo/puddle#2]
Docs for
- NodeJS API 
- Navigator API
- AST
- other libs which are separate from display/render

Docs can be a really concise list of API calls and a short description what does the lib do. 

List of project features by parts:
- NodeJS
- Editor

List of features to be implemented in order of preference.

**Comment by fritzo** [comment]
OK, a concise API reference is now at https://github.com/fritzo/puddle/blob/master/doc/reference.md
