### ISSUE TITLE
gulp-browserify has mocha error on puddle-syntax branch

### ISSUE THREAD

**Issue by fritzo** [fritzo/puddle#7]
Here is the error:

<pre>
$ npm start

> puddle@0.1.6 start /home/fritz/puddle
> gulp serve

[18:58:04] Using gulpfile ~/puddle/gulpfile.js
[18:58:04] Starting 'default'...
[18:58:04] Finished 'default' after 9.76 ms
[18:58:04] Starting 'serve'...
connecting to analyst at tcp://localhost:34936
serving puddle at http://localhost:34934
[18:58:04] Finished 'serve' after 299 ms
Mongoose connected to DB
Uncaught exception: Error in plugin 'gulp-browserify'
module "./runnable" not found from "/home/fritz/puddle/node_modules/mocha/mocha.js"

npm ERR! puddle@0.1.6 start: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puddle@0.1.6 start script.
npm ERR! This is most likely a problem with the puddle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls puddle
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "node" "/usr/bin/npm" "start"
npm ERR! cwd /home/fritz/puddle
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/fritz/puddle/npm-debug.log
npm ERR! not ok code 0
</pre>

**Comment by fritzo** [comment]
@yangit Do you have any tips for debugging gulp? I have not been able to get decent error reporting:

```
npm start
DEBUG=* npm start
gulp --dev=true
```

**Comment by fritzo** [comment]
Even more simply

<pre>
$ browserify server.js 
Error: Cannot find module '../suite' from '/home/fritz/puddle/node_modules/mocha'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:42:25
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:107:15)
</pre>

**Comment by yangit** [comment]
Why would you browserify server.js?

Also I believe that browserify require is working rtlative to the file
where you have require statement unlike node.js where path is relative to
the main script.

Gulp has utils module which you can require and then something
like gulp.utils.log()

I'll look into it once I'm at my computer.

воскресенье, 24 августа 2014 г. пользователь Fritz Obermeyer написал:

**Comment by fritzo** [comment]
> Why would you browserify server.js?
> Um, I must not have been thinking, but broserify main.js fails with the same error.

browserify --exclude mocha main.js does seem to work...
